FROM kitproject/gitpod-flutter-android:lastest
SHELL ["/bin/bash", "-c"]

USER root

# Update system
RUN apt-get update && apt-get upgrade -y
RUN apt-get install python3 python3-pip python3-cryptography less libxext6 libxrender1 libxtst6 libfreetype6 libxi6 -y

USER gitpod

ARG IDEA_VERSION
ARG FLUTTER_PLUGIN_URL
ARG DART_PLUGIN_URL

# add pip PATH
RUN echo 'export PATH=/home/gitpod/.local/bin:$PATH' >>~/.bashrc

# Install IDEA
RUN python3 -m pip install -U pip  && \
    pip3 install projector-installer --upgrade cryptography && \
    /home/gitpod/.local/bin/projector --accept-license autoinstall --config-name "idea" --ide-name "IntelliJ IDEA Community Edition ${IDEA_VERSION}" --use-separate-config && \
    mkdir ~/.projector/configs/idea/plugins && \
    cd ~/.projector/configs/idea/plugins && \
    wget -O flutter-intellij.zip ${FLUTTER_PLUGIN_URL} && \
    unzip flutter-intellij.zip && \
    wget -O Dart.zip ${DART_PLUGIN_URL} && \
    unzip Dart.zip && \
    rm -rf .projector/cache
