FROM kitproject/gitpod-flutter-base:beta
SHELL ["/bin/bash", "-c"]

USER root

# Update system
RUN apt-get update && apt-get upgrade -y

# Install Open JDK
# RUN apt-get install openjdk-8-jdk -y \
#     && update-java-alternatives --set java-1.8.0-openjdk-amd64

USER gitpod

ARG ANDROID_SDK_VERSION

# Install AndroidSDK
ENV ANDROID_HOME=/home/gitpod/android-sdk
RUN cd ~ && \
    wget -O android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_VERSION}_latest.zip && \
    mkdir -p ${ANDROID_HOME}/cmdline-tools && \
    unzip -q android-sdk.zip -d ${ANDROID_HOME}/cmdline-tools/ && \
    rm -rf android-sdk.zip && \
    mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest && \
    cd ${ANDROID_HOME}/cmdline-tools/latest/bin && \
    yes | ./sdkmanager --licenses && \
    ./sdkmanager "tools" "platform-tools"

# add Android PATH
RUN echo 'export PATH=/home/gitpod/android-sdk/cmdline-tools/latest/bin:/home/gitpod/android-sdk/tools:/home/gitpod/android-sdk/platform-tools:/home/gitpod/android-sdk:$PATH' >>~/.bashrc
RUN echo 'export ANDROID_HOME=/home/gitpod/android-sdk' >>~/.bashrc