#!/bin/bash

export FLUTTER_VERSION=3.0.1
export ANDROID_SDK_VERSION=8092744
export ANDROID_NDK_VERSION=r23b
export BUILD_TOOLS_VERSION=32.0.0
export PLATFORMS_VERSION=android-31
export SOURCES_VERSION=android-31
export IDEA_VERSION=2021.3.2
export FLUTTER_PLUGIN_URL="https://plugins.jetbrains.com/files/9212/150278/flutter-intellij.zip?updateId=150278&pluginId=9212&family=INTELLIJ"
export DART_PLUGIN_URL="https://plugins.jetbrains.com/files/6351/145984/Dart-213.5744.122.zip?updateId=145984&pluginId=6351&family=INTELLIJ"
