name: Build Docker

on:
  push:
    branches: [ "create-build-docker" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3

     - name: Run build_docker.sh
       env:
          DOCKER_USER_NAME: ${{ secrets.dockerUserName }}
          DOCKER_PASSWORD: ${{ secrets.dockerPassword }}
       run: ./push_docker.sh

