name: Build Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: push docker
      env:
        DOCKER_USER_NAME: ${{ secrets.dockerUserName }}
        DOCKER_PASSWORD: ${{ secrets.dockerPassword }}
      run: ./push_docker.sh
